### ISSUE TITLE
web menu is missing since 4.1.0 version

### ISSUE THREAD

**Issue by nikolchina** [bsautner/com.nimbits#206]
now nimbits web ui doesn't contain menu with "Rest API", "Log Out" and other buttons.

**Comment by bsautner** [comment]
The "Browse Rest API" link causes a lot of confusion because of the need to add the auth header to your browser.  We removed it - but you can always browse the REST API per this WIKI 

https://github.com/bsautner/com.nimbits/wiki/API:-Overview

Using whatever your host name is - for example http://localhost:8080/service/v3/rest/me

since the web ui does not manage sessions, the logout button didn't do anything - you can just close your browser to end your session - if we introduce sessions into the web portal (so you don't have to login each time) we'll add a logout button

**Comment by nikolchina** [comment]
Ok, I see, so this change has been made not by mistake, although I found that line pretty cute.

**Comment by bsautner** [comment]
thanks :)
